# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainOGC.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userlabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.userlabel.setFont(font)
        self.userlabel.setObjectName("userlabel")
        self.horizontalLayout.addWidget(self.userlabel)
        self.userlineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.userlineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.userlineEdit.setFont(font)
        self.userlineEdit.setStyleSheet("border-radius:15px;")
        self.userlineEdit.setText("")
        self.userlineEdit.setObjectName("userlineEdit")
        self.horizontalLayout.addWidget(self.userlineEdit)
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordlabel = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setObjectName("passwordlabel")
        self.horizontalLayout_2.addWidget(self.passwordlabel)
        self.passwordlineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.passwordlineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordlineEdit.setFont(font)
        self.passwordlineEdit.setStyleSheet("border-radius:15px;")
        self.passwordlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.horizontalLayout_2.addWidget(self.passwordlineEdit)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignBottom)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginpushButton = QtWidgets.QPushButton(self.widget_4)
        self.loginpushButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginpushButton.setFont(font)
        self.loginpushButton.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255,100);\n"
"font: 20pt;\n"
"border-radius:15px;")
        self.loginpushButton.setObjectName("loginpushButton")
        self.verticalLayout_3.addWidget(self.loginpushButton, 0, QtCore.Qt.AlignRight)
        self.createaccountpushButton = QtWidgets.QPushButton(self.widget_4)
        self.createaccountpushButton.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.createaccountpushButton.setFont(font)
        self.createaccountpushButton.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255,100);\n"
"border-radius:15px;\n"
"font: 20pt")
        self.createaccountpushButton.setObjectName("createaccountpushButton")
        self.verticalLayout_3.addWidget(self.createaccountpushButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionbye = QtWidgets.QAction(MainWindow)
        self.actionbye.setObjectName("actionbye")
        self.menu.addAction(self.actionbye)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userlabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">帳號:</span></p></body></html>"))
        self.passwordlabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">密碼:</span></p></body></html>"))
        self.loginpushButton.setText(_translate("MainWindow", "登入"))
        self.createaccountpushButton.setText(_translate("MainWindow", "申請帳號"))
        self.menu.setTitle(_translate("MainWindow", "menu"))
        self.actionbye.setText(_translate("MainWindow", "bye"))
